server:
  port: 8080

spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    # excluded-view-names:
    # template-resolver-order:
    # view-names:
    
  datasource:
    url:  jdbc:mysql://localhost:3306/cair_event?useSSL=false
    username: root
    password: root
    driver-class-name:  com.mysql.jdbc.Driver

logging:
  level:
    root: INFO
    com.example.demo: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.web.FilterChainProxy: INFO 
    org.springframework.jdbc: INFO
    org.springframework.jdbc.core.JdbcTemplate: INFO
    org.springframework.jdbc.core.StatementCreatorUtils: INFO 
    